# Required information
sonar.organization=ua-4790-tc-sq
sonar.projectKey=ua-4790-tc-sq_ua-4790-topic10-codeinspection-node-js-ga-tc
sonar.projectName="SonarCloud Test NodeJS application GitHubActions"
sonar.projectVersion=2.2.0

# Connection details
sonar.host.url=https://sonarcloud.io

# Source code configuration
sonar.sources=./src
sonar.sourceEncoding=UTF-8
sonar.language=js

# Exclusions
sonar.exclusions=**/node_modules/**,**/test/**,**/coverage/**,**/dist/**

# Coverage configuration
sonar.tests=./src/components/test
sonar.javascript.lcov.reportPaths=coverage/lcov.info

